# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cpyrght',
            field=models.CharField(default='buckanjaren', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='commentator',
            field=models.CharField(max_length=30),
        ),
    ]
